name: Platformer Generated test Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: chamod/test
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:${{steps.branch_name.outputs.SOURCE_TAG
          }} --file Dockerfile .
      - name: Docker Push
        run: docker push $SERVICE_NAME:$TAG
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_9516e427-9a3c-4579-bce3-0fee24ac8c55}}
          project-id: ${{secrets.PROJECT_ID_9516e427-9a3c-4579-bce3-0fee24ac8c55}}
          token: ${{secrets.AUTOGENERATED_CICD_9516e427-9a3c-4579-bce3-0fee24ac8c55}}
          image-name: $SERVICE_NAME
          tag: ${{steps.branch_name.outputs.SOURCE_TAG }}
          container-id: f804ebe2-c130-4f6a-8d25-70cfc673bffa
